name = "[Dev] hayato"
url = ""
author = "Hayato Ito"
output_draft_article = "true"
hatena_id = "hayatoito1"
google_analytics_tracking_id = "G-NQ955DMY0H"
github = "https://github.com/hayatoito/hayatoito.github.io/"
